"""
Job writer – persists normalized StandardJob records to the database.
"""

from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.models.job_posting import JobPosting
from app.schemas.standard_job import StandardJob
from app.services.dedup.fingerprint import generate_fingerprint, generate_job_id
from app.services.persistence.company_resolver import resolve_company

logger = get_logger(__name__)


async def write_job(db: AsyncSession, job: StandardJob, run_id: UUID | None) -> JobPosting:
    """Persist a job to the database, resolving company logic first."""
    
    # Generate hashes if not already generated by the dedup service
    # (they usually are, but doing it safely here just in case)
    job_id = job.job_id or generate_job_id(job)
    fingerprint_hash = job.fingerprint_hash or generate_fingerprint(job)
    
    # ── 1. Resolve Company ───────────────────────────────────
    company_id = await resolve_company(db, job.company_name)
    
    # ── 2. Insert Job Record ─────────────────────────────────
    db_job = JobPosting(
        job_id=job_id,
        fingerprint_hash=fingerprint_hash,
        
        title=job.title,
        title_normalized=job.title_normalized,
        
        company_name=job.company_name,
        company_id=company_id,
        
        domain=job.domain or "unknown",
        source_platform=job.source_platform,
        
        actor_id=job.actor_id,
        run_id=run_id,
        
        location_raw=job.location_raw,
        location_city=job.location_city,
        location_country=job.location_country,
        location_region=job.location_region,
        
        salary_raw=job.salary_raw,
        salary_min=job.salary_min,
        salary_max=job.salary_max,
        salary_currency=job.salary_currency,
        
        employment_type=job.employment_type,
        
        experience_years_min=job.experience_years_min,
        experience_years_max=job.experience_years_max,
        
        posted_at=job.posted_at,
        job_url=job.job_url,
        
        description_raw=job.description_raw,
        
        is_duplicate=job.is_duplicate,
    )
    
    db.add(db_job)
    await db.flush()
    logger.info("New job stored: %s at %s", db_job.title, db_job.company_name)
    
    return db_job
