"""add_phone_to_company_contacts

Revision ID: 7ae3267c55db
Revises: 49c0b6348895
Create Date: 2026-03-17 16:36:05.588527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae3267c55db'
down_revision: Union[str, None] = '49c0b6348895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'lead_priority')
    op.drop_column('companies', 'lead_tags')
    op.add_column('company_contacts', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_contacts', 'phone')
    op.add_column('companies', sa.Column('lead_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('lead_priority', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
