"""initial schema

Revision ID: a3c2a669d63e
Revises: 
Create Date: 2026-03-04 23:08:26.729715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3c2a669d63e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_budget_usd', sa.Numeric(), nullable=True),
    sa.Column('spend_mtd_usd', sa.Numeric(), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('apify_input_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalizer_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('company_name_normalized', sa.Text(), nullable=True),
    sa.Column('domains_active', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('platforms_seen_on', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('countries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_postings_alltime', sa.Integer(), nullable=False),
    sa.Column('total_postings_7d', sa.Integer(), nullable=False),
    sa.Column('total_postings_30d', sa.Integer(), nullable=False),
    sa.Column('avg_postings_30d', sa.Numeric(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_repeat_poster', sa.Boolean(), nullable=False),
    sa.Column('repeated_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('hiring_velocity_score', sa.Numeric(), nullable=False),
    sa.Column('bd_priority_score', sa.Numeric(), nullable=False),
    sa.Column('bd_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apollo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('employee_count', sa.Text(), nullable=True),
    sa.Column('industry_apollo', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('hq_country', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name_normalized')
    )
    op.create_index('ix_companies_bd_priority_score', 'companies', [sa.literal_column('bd_priority_score DESC')], unique=False)
    op.create_index(op.f('ix_companies_is_enriched'), 'companies', ['is_enriched'], unique=False)
    op.create_index(op.f('ix_companies_last_active_at'), 'companies', ['last_active_at'], unique=False)
    op.create_table('daily_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('companies_spiking', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companies_struggling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_entrants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('domain_surges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ghost_posters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_companies_by_domain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_jobs_today', sa.Integer(), nullable=True),
    sa.Column('total_companies_active_today', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insight_date')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('fingerprint_hash', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_normalized', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('source_platform', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_country', sa.Text(), nullable=True),
    sa.Column('location_region', sa.Text(), nullable=True),
    sa.Column('salary_raw', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('salary_currency', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('experience_years_max', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_domain'), 'job_postings', ['domain'], unique=False)
    op.create_index(op.f('ix_job_postings_fingerprint_hash'), 'job_postings', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_job_postings_location_country'), 'job_postings', ['location_country'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_source_platform'), 'job_postings', ['source_platform'], unique=False)
    op.create_table('actor_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_config_id', sa.UUID(), nullable=True),
    sa.Column('apify_run_id', sa.Text(), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('total_scraped', sa.Integer(), nullable=False),
    sa.Column('total_new', sa.Integer(), nullable=False),
    sa.Column('total_duplicates', sa.Integer(), nullable=False),
    sa.Column('total_cross_dupes', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('compute_units_used', sa.Numeric(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_config_id'], ['actor_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_runs_actor_config_id'), 'actor_runs', ['actor_config_id'], unique=False)
    op.create_index(op.f('ix_actor_runs_run_date'), 'actor_runs', ['run_date'], unique=False)
    op.create_index(op.f('ix_actor_runs_status'), 'actor_runs', ['status'], unique=False)
    op.create_table('enrichment_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('apollo_org_id', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('employee_count', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('revenue_range', sa.Text(), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('enriched_by', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrichment_cache')
    op.drop_index(op.f('ix_actor_runs_status'), table_name='actor_runs')
    op.drop_index(op.f('ix_actor_runs_run_date'), table_name='actor_runs')
    op.drop_index(op.f('ix_actor_runs_actor_config_id'), table_name='actor_runs')
    op.drop_table('actor_runs')
    op.drop_index(op.f('ix_job_postings_source_platform'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_location_country'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_fingerprint_hash'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_domain'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_table('daily_insights')
    op.drop_index(op.f('ix_companies_last_active_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_enriched'), table_name='companies')
    op.drop_index('ix_companies_bd_priority_score', table_name='companies')
    op.drop_table('companies')
    op.drop_table('actor_configs')
    # ### end Alembic commands ###
