"""Add is_confidential column to companies table.

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 20:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = "b2c3d4e5f6g7"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_confidential', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('ix_companies_is_confidential', 'companies', ['is_confidential'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_is_confidential', table_name='companies')
    op.drop_column('companies', 'is_confidential')
    # ### end Alembic commands ###
