"""hubspot_sync_columns

Revision ID: c9f4a12b8e3d
Revises: 7ae3267c55db
Create Date: 2026-03-17 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f4a12b8e3d'
down_revision: Union[str, None] = '7ae3267c55db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column(
        'hubspot_company_id', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column(
        'hubspot_deal_id', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column(
        'hubspot_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        'ix_companies_hubspot_company_id',
        'companies', ['hubspot_company_id'], unique=False)
    op.add_column('company_contacts', sa.Column(
        'hubspot_contact_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_companies_hubspot_company_id', table_name='companies')
    op.drop_column('company_contacts', 'hubspot_contact_id')
    op.drop_column('companies', 'hubspot_synced_at')
    op.drop_column('companies', 'hubspot_deal_id')
    op.drop_column('companies', 'hubspot_company_id')
    # ### end Alembic commands ###
