"""Add system_settings table for persistent API key storage.

Revision ID: a1b2c3d4e5f6
Revises: c9f4a12b8e3d
Create Date: 2026-03-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = "a1b2c3d4e5f6"
down_revision = "c9f4a12b8e3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column(
            "setting_key",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "setting_value",
            sa.String(2048),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("setting_key"),
    )
    op.create_index("idx_setting_key", "system_settings", ["setting_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_setting_key", table_name="system_settings")
    op.drop_table("system_settings")
    # ### end Alembic commands ###
